// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.1
// source: services/billing-service/proto/billing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanType      string                 `protobuf:"bytes,2,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_services_billing_service_proto_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

type GetSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_services_billing_service_proto_billing_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SubscriptionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanType         string                 `protobuf:"bytes,3,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	RequestsPerMonth int32                  `protobuf:"varint,4,opt,name=requests_per_month,json=requestsPerMonth,proto3" json:"requests_per_month,omitempty"`
	RequestsUsed     int32                  `protobuf:"varint,5,opt,name=requests_used,json=requestsUsed,proto3" json:"requests_used,omitempty"`
	Price            float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	IsActive         bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_services_billing_service_proto_billing_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscriptionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscriptionResponse) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

func (x *SubscriptionResponse) GetRequestsPerMonth() int32 {
	if x != nil {
		return x.RequestsPerMonth
	}
	return 0
}

func (x *SubscriptionResponse) GetRequestsUsed() int32 {
	if x != nil {
		return x.RequestsUsed
	}
	return 0
}

func (x *SubscriptionResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SubscriptionResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CheckQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQuotaRequest) Reset() {
	*x = CheckQuotaRequest{}
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaRequest) ProtoMessage() {}

func (x *CheckQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaRequest.ProtoReflect.Descriptor instead.
func (*CheckQuotaRequest) Descriptor() ([]byte, []int) {
	return file_services_billing_service_proto_billing_proto_rawDescGZIP(), []int{3}
}

func (x *CheckQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasQuota      bool                   `protobuf:"varint,1,opt,name=has_quota,json=hasQuota,proto3" json:"has_quota,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQuotaResponse) Reset() {
	*x = CheckQuotaResponse{}
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaResponse) ProtoMessage() {}

func (x *CheckQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaResponse.ProtoReflect.Descriptor instead.
func (*CheckQuotaResponse) Descriptor() ([]byte, []int) {
	return file_services_billing_service_proto_billing_proto_rawDescGZIP(), []int{4}
}

func (x *CheckQuotaResponse) GetHasQuota() bool {
	if x != nil {
		return x.HasQuota
	}
	return false
}

func (x *CheckQuotaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IncrementUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementUsageRequest) Reset() {
	*x = IncrementUsageRequest{}
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementUsageRequest) ProtoMessage() {}

func (x *IncrementUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementUsageRequest.ProtoReflect.Descriptor instead.
func (*IncrementUsageRequest) Descriptor() ([]byte, []int) {
	return file_services_billing_service_proto_billing_proto_rawDescGZIP(), []int{5}
}

func (x *IncrementUsageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IncrementUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementUsageResponse) Reset() {
	*x = IncrementUsageResponse{}
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementUsageResponse) ProtoMessage() {}

func (x *IncrementUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_billing_service_proto_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementUsageResponse.ProtoReflect.Descriptor instead.
func (*IncrementUsageResponse) Descriptor() ([]byte, []int) {
	return file_services_billing_service_proto_billing_proto_rawDescGZIP(), []int{6}
}

func (x *IncrementUsageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_services_billing_service_proto_billing_proto protoreflect.FileDescriptor

const file_services_billing_service_proto_billing_proto_rawDesc = "" +
	"\n" +
	",services/billing-service/proto/billing.proto\x12\abilling\"Q\n" +
	"\x19CreateSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tplan_type\x18\x02 \x01(\tR\bplanType\"1\n" +
	"\x16GetSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xe2\x01\n" +
	"\x14SubscriptionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tplan_type\x18\x03 \x01(\tR\bplanType\x12,\n" +
	"\x12requests_per_month\x18\x04 \x01(\x05R\x10requestsPerMonth\x12#\n" +
	"\rrequests_used\x18\x05 \x01(\x05R\frequestsUsed\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\",\n" +
	"\x11CheckQuotaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"K\n" +
	"\x12CheckQuotaResponse\x12\x1b\n" +
	"\thas_quota\x18\x01 \x01(\bR\bhasQuota\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x15IncrementUsageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\x16IncrementUsageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd6\x02\n" +
	"\x0eBillingService\x12W\n" +
	"\x12CreateSubscription\x12\".billing.CreateSubscriptionRequest\x1a\x1d.billing.SubscriptionResponse\x12Q\n" +
	"\x0fGetSubscription\x12\x1f.billing.GetSubscriptionRequest\x1a\x1d.billing.SubscriptionResponse\x12E\n" +
	"\n" +
	"CheckQuota\x12\x1a.billing.CheckQuotaRequest\x1a\x1b.billing.CheckQuotaResponse\x12Q\n" +
	"\x0eIncrementUsage\x12\x1e.billing.IncrementUsageRequest\x1a\x1f.billing.IncrementUsageResponseB0Z.quicknode-clone/services/billing-service/protob\x06proto3"

var (
	file_services_billing_service_proto_billing_proto_rawDescOnce sync.Once
	file_services_billing_service_proto_billing_proto_rawDescData []byte
)

func file_services_billing_service_proto_billing_proto_rawDescGZIP() []byte {
	file_services_billing_service_proto_billing_proto_rawDescOnce.Do(func() {
		file_services_billing_service_proto_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_billing_service_proto_billing_proto_rawDesc), len(file_services_billing_service_proto_billing_proto_rawDesc)))
	})
	return file_services_billing_service_proto_billing_proto_rawDescData
}

var file_services_billing_service_proto_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_billing_service_proto_billing_proto_goTypes = []any{
	(*CreateSubscriptionRequest)(nil), // 0: billing.CreateSubscriptionRequest
	(*GetSubscriptionRequest)(nil),    // 1: billing.GetSubscriptionRequest
	(*SubscriptionResponse)(nil),      // 2: billing.SubscriptionResponse
	(*CheckQuotaRequest)(nil),         // 3: billing.CheckQuotaRequest
	(*CheckQuotaResponse)(nil),        // 4: billing.CheckQuotaResponse
	(*IncrementUsageRequest)(nil),     // 5: billing.IncrementUsageRequest
	(*IncrementUsageResponse)(nil),    // 6: billing.IncrementUsageResponse
}
var file_services_billing_service_proto_billing_proto_depIdxs = []int32{
	0, // 0: billing.BillingService.CreateSubscription:input_type -> billing.CreateSubscriptionRequest
	1, // 1: billing.BillingService.GetSubscription:input_type -> billing.GetSubscriptionRequest
	3, // 2: billing.BillingService.CheckQuota:input_type -> billing.CheckQuotaRequest
	5, // 3: billing.BillingService.IncrementUsage:input_type -> billing.IncrementUsageRequest
	2, // 4: billing.BillingService.CreateSubscription:output_type -> billing.SubscriptionResponse
	2, // 5: billing.BillingService.GetSubscription:output_type -> billing.SubscriptionResponse
	4, // 6: billing.BillingService.CheckQuota:output_type -> billing.CheckQuotaResponse
	6, // 7: billing.BillingService.IncrementUsage:output_type -> billing.IncrementUsageResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_billing_service_proto_billing_proto_init() }
func file_services_billing_service_proto_billing_proto_init() {
	if File_services_billing_service_proto_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_billing_service_proto_billing_proto_rawDesc), len(file_services_billing_service_proto_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_billing_service_proto_billing_proto_goTypes,
		DependencyIndexes: file_services_billing_service_proto_billing_proto_depIdxs,
		MessageInfos:      file_services_billing_service_proto_billing_proto_msgTypes,
	}.Build()
	File_services_billing_service_proto_billing_proto = out.File
	file_services_billing_service_proto_billing_proto_goTypes = nil
	file_services_billing_service_proto_billing_proto_depIdxs = nil
}
