// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.1
// source: services/user-service/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_services_user_service_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAPIKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIKeysRequest) Reset() {
	*x = GetAPIKeysRequest{}
	mi := &file_services_user_service_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIKeysRequest) ProtoMessage() {}

func (x *GetAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*GetAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetAPIKeysRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type APIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyResponse) Reset() {
	*x = APIKeyResponse{}
	mi := &file_services_user_service_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyResponse) ProtoMessage() {}

func (x *APIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyResponse.ProtoReflect.Descriptor instead.
func (*APIKeyResponse) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *APIKeyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKeyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *APIKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *APIKeyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeyResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *APIKeyResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*APIKeyResponse      `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIKeysResponse) Reset() {
	*x = GetAPIKeysResponse{}
	mi := &file_services_user_service_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIKeysResponse) ProtoMessage() {}

func (x *GetAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*GetAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetAPIKeysResponse) GetApiKeys() []*APIKeyResponse {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_services_user_service_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateAPIKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ValidateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_services_user_service_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateAPIKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPIKeyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyRequest) Reset() {
	*x = DeleteAPIKeyRequest{}
	mi := &file_services_user_service_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyRequest) ProtoMessage() {}

func (x *DeleteAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyResponse) Reset() {
	*x = DeleteAPIKeyResponse{}
	mi := &file_services_user_service_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyResponse) ProtoMessage() {}

func (x *DeleteAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAPIKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_services_user_service_proto_user_proto protoreflect.FileDescriptor

const file_services_user_service_proto_user_proto_rawDesc = "" +
	"\n" +
	"&services/user-service/proto/user.proto\x12\x04user\"d\n" +
	"\x13CreateAPIKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\",\n" +
	"\x11GetAPIKeysRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9e\x01\n" +
	"\x0eAPIKeyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"E\n" +
	"\x12GetAPIKeysResponse\x12/\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x14.user.APIKeyResponseR\aapiKeys\")\n" +
	"\x15ValidateAPIKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"G\n" +
	"\x16ValidateAPIKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"%\n" +
	"\x13DeleteAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteAPIKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa3\x02\n" +
	"\vUserService\x12?\n" +
	"\fCreateAPIKey\x12\x19.user.CreateAPIKeyRequest\x1a\x14.user.APIKeyResponse\x12?\n" +
	"\n" +
	"GetAPIKeys\x12\x17.user.GetAPIKeysRequest\x1a\x18.user.GetAPIKeysResponse\x12K\n" +
	"\x0eValidateAPIKey\x12\x1b.user.ValidateAPIKeyRequest\x1a\x1c.user.ValidateAPIKeyResponse\x12E\n" +
	"\fDeleteAPIKey\x12\x19.user.DeleteAPIKeyRequest\x1a\x1a.user.DeleteAPIKeyResponseB-Z+quicknode-clone/services/user-service/protob\x06proto3"

var (
	file_services_user_service_proto_user_proto_rawDescOnce sync.Once
	file_services_user_service_proto_user_proto_rawDescData []byte
)

func file_services_user_service_proto_user_proto_rawDescGZIP() []byte {
	file_services_user_service_proto_user_proto_rawDescOnce.Do(func() {
		file_services_user_service_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_user_service_proto_user_proto_rawDesc), len(file_services_user_service_proto_user_proto_rawDesc)))
	})
	return file_services_user_service_proto_user_proto_rawDescData
}

var file_services_user_service_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_services_user_service_proto_user_proto_goTypes = []any{
	(*CreateAPIKeyRequest)(nil),    // 0: user.CreateAPIKeyRequest
	(*GetAPIKeysRequest)(nil),      // 1: user.GetAPIKeysRequest
	(*APIKeyResponse)(nil),         // 2: user.APIKeyResponse
	(*GetAPIKeysResponse)(nil),     // 3: user.GetAPIKeysResponse
	(*ValidateAPIKeyRequest)(nil),  // 4: user.ValidateAPIKeyRequest
	(*ValidateAPIKeyResponse)(nil), // 5: user.ValidateAPIKeyResponse
	(*DeleteAPIKeyRequest)(nil),    // 6: user.DeleteAPIKeyRequest
	(*DeleteAPIKeyResponse)(nil),   // 7: user.DeleteAPIKeyResponse
}
var file_services_user_service_proto_user_proto_depIdxs = []int32{
	2, // 0: user.GetAPIKeysResponse.api_keys:type_name -> user.APIKeyResponse
	0, // 1: user.UserService.CreateAPIKey:input_type -> user.CreateAPIKeyRequest
	1, // 2: user.UserService.GetAPIKeys:input_type -> user.GetAPIKeysRequest
	4, // 3: user.UserService.ValidateAPIKey:input_type -> user.ValidateAPIKeyRequest
	6, // 4: user.UserService.DeleteAPIKey:input_type -> user.DeleteAPIKeyRequest
	2, // 5: user.UserService.CreateAPIKey:output_type -> user.APIKeyResponse
	3, // 6: user.UserService.GetAPIKeys:output_type -> user.GetAPIKeysResponse
	5, // 7: user.UserService.ValidateAPIKey:output_type -> user.ValidateAPIKeyResponse
	7, // 8: user.UserService.DeleteAPIKey:output_type -> user.DeleteAPIKeyResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_user_service_proto_user_proto_init() }
func file_services_user_service_proto_user_proto_init() {
	if File_services_user_service_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_user_service_proto_user_proto_rawDesc), len(file_services_user_service_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_user_service_proto_user_proto_goTypes,
		DependencyIndexes: file_services_user_service_proto_user_proto_depIdxs,
		MessageInfos:      file_services_user_service_proto_user_proto_msgTypes,
	}.Build()
	File_services_user_service_proto_user_proto = out.File
	file_services_user_service_proto_user_proto_goTypes = nil
	file_services_user_service_proto_user_proto_depIdxs = nil
}
