// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.1
// source: services/blockchain-service/proto/blockchain.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_services_blockchain_service_proto_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateNodeRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CreateNodeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_services_blockchain_service_proto_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_services_blockchain_service_proto_blockchain_proto_rawDescGZIP(), []int{2}
}

type GetNodesByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesByTypeRequest) Reset() {
	*x = GetNodesByTypeRequest{}
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesByTypeRequest) ProtoMessage() {}

func (x *GetNodesByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetNodesByTypeRequest) Descriptor() ([]byte, []int) {
	return file_services_blockchain_service_proto_blockchain_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodesByTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Network       string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_services_blockchain_service_proto_blockchain_proto_rawDescGZIP(), []int{4}
}

func (x *NodeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NodeResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NodeResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *NodeResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeResponse        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockchain_service_proto_blockchain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_services_blockchain_service_proto_blockchain_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesResponse) GetNodes() []*NodeResponse {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_services_blockchain_service_proto_blockchain_proto protoreflect.FileDescriptor

const file_services_blockchain_service_proto_blockchain_proto_rawDesc = "" +
	"\n" +
	"2services/blockchain-service/proto/blockchain.proto\x12\n" +
	"blockchain\"g\n" +
	"\x11CreateNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\" \n" +
	"\x0eGetNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10ListNodesRequest\"+\n" +
	"\x15GetNodesByTypeRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"\xab\x01\n" +
	"\fNodeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\"C\n" +
	"\x11ListNodesResponse\x12.\n" +
	"\x05nodes\x18\x01 \x03(\v2\x18.blockchain.NodeResponseR\x05nodes2\xb9\x02\n" +
	"\x11BlockchainService\x12E\n" +
	"\n" +
	"CreateNode\x12\x1d.blockchain.CreateNodeRequest\x1a\x18.blockchain.NodeResponse\x12?\n" +
	"\aGetNode\x12\x1a.blockchain.GetNodeRequest\x1a\x18.blockchain.NodeResponse\x12H\n" +
	"\tListNodes\x12\x1c.blockchain.ListNodesRequest\x1a\x1d.blockchain.ListNodesResponse\x12R\n" +
	"\x0eGetNodesByType\x12!.blockchain.GetNodesByTypeRequest\x1a\x1d.blockchain.ListNodesResponseB3Z1quicknode-clone/services/blockchain-service/protob\x06proto3"

var (
	file_services_blockchain_service_proto_blockchain_proto_rawDescOnce sync.Once
	file_services_blockchain_service_proto_blockchain_proto_rawDescData []byte
)

func file_services_blockchain_service_proto_blockchain_proto_rawDescGZIP() []byte {
	file_services_blockchain_service_proto_blockchain_proto_rawDescOnce.Do(func() {
		file_services_blockchain_service_proto_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_blockchain_service_proto_blockchain_proto_rawDesc), len(file_services_blockchain_service_proto_blockchain_proto_rawDesc)))
	})
	return file_services_blockchain_service_proto_blockchain_proto_rawDescData
}

var file_services_blockchain_service_proto_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_blockchain_service_proto_blockchain_proto_goTypes = []any{
	(*CreateNodeRequest)(nil),     // 0: blockchain.CreateNodeRequest
	(*GetNodeRequest)(nil),        // 1: blockchain.GetNodeRequest
	(*ListNodesRequest)(nil),      // 2: blockchain.ListNodesRequest
	(*GetNodesByTypeRequest)(nil), // 3: blockchain.GetNodesByTypeRequest
	(*NodeResponse)(nil),          // 4: blockchain.NodeResponse
	(*ListNodesResponse)(nil),     // 5: blockchain.ListNodesResponse
}
var file_services_blockchain_service_proto_blockchain_proto_depIdxs = []int32{
	4, // 0: blockchain.ListNodesResponse.nodes:type_name -> blockchain.NodeResponse
	0, // 1: blockchain.BlockchainService.CreateNode:input_type -> blockchain.CreateNodeRequest
	1, // 2: blockchain.BlockchainService.GetNode:input_type -> blockchain.GetNodeRequest
	2, // 3: blockchain.BlockchainService.ListNodes:input_type -> blockchain.ListNodesRequest
	3, // 4: blockchain.BlockchainService.GetNodesByType:input_type -> blockchain.GetNodesByTypeRequest
	4, // 5: blockchain.BlockchainService.CreateNode:output_type -> blockchain.NodeResponse
	4, // 6: blockchain.BlockchainService.GetNode:output_type -> blockchain.NodeResponse
	5, // 7: blockchain.BlockchainService.ListNodes:output_type -> blockchain.ListNodesResponse
	5, // 8: blockchain.BlockchainService.GetNodesByType:output_type -> blockchain.ListNodesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_blockchain_service_proto_blockchain_proto_init() }
func file_services_blockchain_service_proto_blockchain_proto_init() {
	if File_services_blockchain_service_proto_blockchain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_blockchain_service_proto_blockchain_proto_rawDesc), len(file_services_blockchain_service_proto_blockchain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_blockchain_service_proto_blockchain_proto_goTypes,
		DependencyIndexes: file_services_blockchain_service_proto_blockchain_proto_depIdxs,
		MessageInfos:      file_services_blockchain_service_proto_blockchain_proto_msgTypes,
	}.Build()
	File_services_blockchain_service_proto_blockchain_proto = out.File
	file_services_blockchain_service_proto_blockchain_proto_goTypes = nil
	file_services_blockchain_service_proto_blockchain_proto_depIdxs = nil
}
