// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.1
// source: services/analytics-service/proto/analytics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AnalyticsService_LogRequest_FullMethodName        = "/analytics.AnalyticsService/LogRequest"
	AnalyticsService_GetRequestHistory_FullMethodName = "/analytics.AnalyticsService/GetRequestHistory"
	AnalyticsService_GetUsageStats_FullMethodName     = "/analytics.AnalyticsService/GetUsageStats"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	LogRequest(ctx context.Context, in *LogRequestRequest, opts ...grpc.CallOption) (*LogRequestResponse, error)
	GetRequestHistory(ctx context.Context, in *GetRequestHistoryRequest, opts ...grpc.CallOption) (*GetRequestHistoryResponse, error)
	GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*GetUsageStatsResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) LogRequest(ctx context.Context, in *LogRequestRequest, opts ...grpc.CallOption) (*LogRequestResponse, error) {
	out := new(LogRequestResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_LogRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRequestHistory(ctx context.Context, in *GetRequestHistoryRequest, opts ...grpc.CallOption) (*GetRequestHistoryResponse, error) {
	out := new(GetRequestHistoryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetRequestHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*GetUsageStatsResponse, error) {
	out := new(GetUsageStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetUsageStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility
type AnalyticsServiceServer interface {
	LogRequest(context.Context, *LogRequestRequest) (*LogRequestResponse, error)
	GetRequestHistory(context.Context, *GetRequestHistoryRequest) (*GetRequestHistoryResponse, error)
	GetUsageStats(context.Context, *GetUsageStatsRequest) (*GetUsageStatsResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServiceServer struct {
}

func (UnimplementedAnalyticsServiceServer) LogRequest(context.Context, *LogRequestRequest) (*LogRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogRequest not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRequestHistory(context.Context, *GetRequestHistoryRequest) (*GetRequestHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequestHistory not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetUsageStats(context.Context, *GetUsageStatsRequest) (*GetUsageStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsageStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_LogRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).LogRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_LogRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).LogRequest(ctx, req.(*LogRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRequestHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetRequestHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetRequestHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetRequestHistory(ctx, req.(*GetRequestHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetUsageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetUsageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetUsageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetUsageStats(ctx, req.(*GetUsageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogRequest",
			Handler:    _AnalyticsService_LogRequest_Handler,
		},
		{
			MethodName: "GetRequestHistory",
			Handler:    _AnalyticsService_GetRequestHistory_Handler,
		},
		{
			MethodName: "GetUsageStats",
			Handler:    _AnalyticsService_GetUsageStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/analytics-service/proto/analytics.proto",
}
