// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.1
// source: services/analytics-service/proto/analytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKeyId      string                 `protobuf:"bytes,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	Blockchain    string                 `protobuf:"bytes,3,opt,name=blockchain,proto3" json:"blockchain,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	StatusCode    int32                  `protobuf:"varint,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResponseTime  int64                  `protobuf:"varint,7,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	RequestSize   int64                  `protobuf:"varint,8,opt,name=request_size,json=requestSize,proto3" json:"request_size,omitempty"`
	ResponseSize  int64                  `protobuf:"varint,9,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	IpAddress     string                 `protobuf:"bytes,10,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Error         string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequestRequest) Reset() {
	*x = LogRequestRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequestRequest) ProtoMessage() {}

func (x *LogRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequestRequest.ProtoReflect.Descriptor instead.
func (*LogRequestRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogRequestRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *LogRequestRequest) GetBlockchain() string {
	if x != nil {
		return x.Blockchain
	}
	return ""
}

func (x *LogRequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogRequestRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *LogRequestRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LogRequestRequest) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *LogRequestRequest) GetRequestSize() int64 {
	if x != nil {
		return x.RequestSize
	}
	return 0
}

func (x *LogRequestRequest) GetResponseSize() int64 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *LogRequestRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LogRequestRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LogRequestRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequestResponse) Reset() {
	*x = LogRequestResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequestResponse) ProtoMessage() {}

func (x *LogRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequestResponse.ProtoReflect.Descriptor instead.
func (*LogRequestResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *LogRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequestHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestHistoryRequest) Reset() {
	*x = GetRequestHistoryRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestHistoryRequest) ProtoMessage() {}

func (x *GetRequestHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetRequestHistoryRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequestHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRequestHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRequestHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*RequestLog          `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestHistoryResponse) Reset() {
	*x = GetRequestHistoryResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestHistoryResponse) ProtoMessage() {}

func (x *GetRequestHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetRequestHistoryResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequestHistoryResponse) GetLogs() []*RequestLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type RequestLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKeyId      string                 `protobuf:"bytes,3,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	Blockchain    string                 `protobuf:"bytes,4,opt,name=blockchain,proto3" json:"blockchain,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Endpoint      string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	StatusCode    int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResponseTime  int64                  `protobuf:"varint,8,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	RequestSize   int64                  `protobuf:"varint,9,opt,name=request_size,json=requestSize,proto3" json:"request_size,omitempty"`
	ResponseSize  int64                  `protobuf:"varint,10,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	IpAddress     string                 `protobuf:"bytes,11,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,12,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Error         string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLog) Reset() {
	*x = RequestLog{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLog) ProtoMessage() {}

func (x *RequestLog) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLog.ProtoReflect.Descriptor instead.
func (*RequestLog) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *RequestLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestLog) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *RequestLog) GetBlockchain() string {
	if x != nil {
		return x.Blockchain
	}
	return ""
}

func (x *RequestLog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestLog) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RequestLog) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RequestLog) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *RequestLog) GetRequestSize() int64 {
	if x != nil {
		return x.RequestSize
	}
	return 0
}

func (x *RequestLog) GetResponseSize() int64 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *RequestLog) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RequestLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RequestLog) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RequestLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetUsageStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageStatsRequest) Reset() {
	*x = GetUsageStatsRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageStatsRequest) ProtoMessage() {}

func (x *GetUsageStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUsageStatsRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsageStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUsageStatsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetUsageStatsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetUsageStatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests       int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulRequests  int64                  `protobuf:"varint,2,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	SuccessRate         float64                `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AverageResponseTime int64                  `protobuf:"varint,4,opt,name=average_response_time,json=averageResponseTime,proto3" json:"average_response_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetUsageStatsResponse) Reset() {
	*x = GetUsageStatsResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageStatsResponse) ProtoMessage() {}

func (x *GetUsageStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUsageStatsResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsageStatsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *GetUsageStatsResponse) GetSuccessfulRequests() int64 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *GetUsageStatsResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *GetUsageStatsResponse) GetAverageResponseTime() int64 {
	if x != nil {
		return x.AverageResponseTime
	}
	return 0
}

var File_services_analytics_service_proto_analytics_proto protoreflect.FileDescriptor

const file_services_analytics_service_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"0services/analytics-service/proto/analytics.proto\x12\tanalytics\"\x80\x03\n" +
	"\x11LogRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\tR\bapiKeyId\x12\x1e\n" +
	"\n" +
	"blockchain\x18\x03 \x01(\tR\n" +
	"blockchain\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rresponse_time\x18\a \x01(\x03R\fresponseTime\x12!\n" +
	"\frequest_size\x18\b \x01(\x03R\vrequestSize\x12#\n" +
	"\rresponse_size\x18\t \x01(\x03R\fresponseSize\x12\x1d\n" +
	"\n" +
	"ip_address\x18\n" +
	" \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\".\n" +
	"\x12LogRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x18GetRequestHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"F\n" +
	"\x19GetRequestHistoryResponse\x12)\n" +
	"\x04logs\x18\x01 \x03(\v2\x15.analytics.RequestLogR\x04logs\"\xa8\x03\n" +
	"\n" +
	"RequestLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x03 \x01(\tR\bapiKeyId\x12\x1e\n" +
	"\n" +
	"blockchain\x18\x04 \x01(\tR\n" +
	"blockchain\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rresponse_time\x18\b \x01(\x03R\fresponseTime\x12!\n" +
	"\frequest_size\x18\t \x01(\x03R\vrequestSize\x12#\n" +
	"\rresponse_size\x18\n" +
	" \x01(\x03R\fresponseSize\x12\x1d\n" +
	"\n" +
	"ip_address\x18\v \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\f \x01(\tR\tuserAgent\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\"i\n" +
	"\x14GetUsageStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\xc6\x01\n" +
	"\x15GetUsageStatsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12/\n" +
	"\x13successful_requests\x18\x02 \x01(\x03R\x12successfulRequests\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x01R\vsuccessRate\x122\n" +
	"\x15average_response_time\x18\x04 \x01(\x03R\x13averageResponseTime2\x91\x02\n" +
	"\x10AnalyticsService\x12I\n" +
	"\n" +
	"LogRequest\x12\x1c.analytics.LogRequestRequest\x1a\x1d.analytics.LogRequestResponse\x12^\n" +
	"\x11GetRequestHistory\x12#.analytics.GetRequestHistoryRequest\x1a$.analytics.GetRequestHistoryResponse\x12R\n" +
	"\rGetUsageStats\x12\x1f.analytics.GetUsageStatsRequest\x1a .analytics.GetUsageStatsResponseB2Z0quicknode-clone/services/analytics-service/protob\x06proto3"

var (
	file_services_analytics_service_proto_analytics_proto_rawDescOnce sync.Once
	file_services_analytics_service_proto_analytics_proto_rawDescData []byte
)

func file_services_analytics_service_proto_analytics_proto_rawDescGZIP() []byte {
	file_services_analytics_service_proto_analytics_proto_rawDescOnce.Do(func() {
		file_services_analytics_service_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_analytics_service_proto_analytics_proto_rawDesc), len(file_services_analytics_service_proto_analytics_proto_rawDesc)))
	})
	return file_services_analytics_service_proto_analytics_proto_rawDescData
}

var file_services_analytics_service_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_analytics_service_proto_analytics_proto_goTypes = []any{
	(*LogRequestRequest)(nil),         // 0: analytics.LogRequestRequest
	(*LogRequestResponse)(nil),        // 1: analytics.LogRequestResponse
	(*GetRequestHistoryRequest)(nil),  // 2: analytics.GetRequestHistoryRequest
	(*GetRequestHistoryResponse)(nil), // 3: analytics.GetRequestHistoryResponse
	(*RequestLog)(nil),                // 4: analytics.RequestLog
	(*GetUsageStatsRequest)(nil),      // 5: analytics.GetUsageStatsRequest
	(*GetUsageStatsResponse)(nil),     // 6: analytics.GetUsageStatsResponse
}
var file_services_analytics_service_proto_analytics_proto_depIdxs = []int32{
	4, // 0: analytics.GetRequestHistoryResponse.logs:type_name -> analytics.RequestLog
	0, // 1: analytics.AnalyticsService.LogRequest:input_type -> analytics.LogRequestRequest
	2, // 2: analytics.AnalyticsService.GetRequestHistory:input_type -> analytics.GetRequestHistoryRequest
	5, // 3: analytics.AnalyticsService.GetUsageStats:input_type -> analytics.GetUsageStatsRequest
	1, // 4: analytics.AnalyticsService.LogRequest:output_type -> analytics.LogRequestResponse
	3, // 5: analytics.AnalyticsService.GetRequestHistory:output_type -> analytics.GetRequestHistoryResponse
	6, // 6: analytics.AnalyticsService.GetUsageStats:output_type -> analytics.GetUsageStatsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_analytics_service_proto_analytics_proto_init() }
func file_services_analytics_service_proto_analytics_proto_init() {
	if File_services_analytics_service_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_analytics_service_proto_analytics_proto_rawDesc), len(file_services_analytics_service_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_analytics_service_proto_analytics_proto_goTypes,
		DependencyIndexes: file_services_analytics_service_proto_analytics_proto_depIdxs,
		MessageInfos:      file_services_analytics_service_proto_analytics_proto_msgTypes,
	}.Build()
	File_services_analytics_service_proto_analytics_proto = out.File
	file_services_analytics_service_proto_analytics_proto_goTypes = nil
	file_services_analytics_service_proto_analytics_proto_depIdxs = nil
}
